### ISSUE TITLE
Unicode decoding issues

### ISSUE THREAD

**Issue by ekurutepe** [orlandos-nl/IkigaJSON#27]
On iOS, I'm running into issues decoding `\u2019` and probably others as well. 
`\u2019` is getting decoded as "I2019d delete the email"
And another string which is decoded as "‘Try not to step on any toads!’: David Attenborough’s camera wizards on how to film Britain’s wildlife" by Foundation returns nil with Ikiga. Not sure if the issue is caused by `\u8216` or `\u8217`.

**Comment by Joannis** [comment]
@ekurutepe thanks for reporting the issue, can you please wrap your bug in a test case? I'll make sure it's fixed then.

**Comment by sliemeobn** [comment]
I am seeing all sorts of unicode weirdness on linux (swift 5.8 docker image) as well.
Since I have a lot of German text to process, this get wild quickly. It seems to struggle with umlauts like üäö ÜÄÖ and ß.
I noticed it because I saw stuff like `Gu\u00DFteil` instead of Gußteil, or `G00D6WEIL` instead of GÖWEIL in my production logs. Sometimes decoding to `AnyCodable` fails completely, other times it works but with incorrect string values.

I am lucky that the payload is forwarded to another nodejs service for processing, which seems to reverse-glitchify the encoding somehow...

**Comment by Joannis** [comment]
@sliemeobn , thanks for the heads up. I'm currently taking care of my newborn, but if you can make some tests for your use cases I can sort it when I hve time.

**Comment by sliemeobn** [comment]
congratulations! babies > code ; )

I tried all afternoon but I couldn't get a test done that would show the issue. also, no matter what I throw at our staging env myself causes any issues (even the cräzießt German). I am in the process of adding more logging to our production env to see what requests are coming in exactly... it is very strange...

**Comment by Joannis** [comment]
Hmm, if you want you can get in touch with my colleague Robbert ( @obbut ) through our [discord group](https://discord.gg/H6799jh). If he has time, maybe he can help you out right now.

**Comment by sliemeobn** [comment]
I finally figured out what causes the issue: it is not the encoding of the JSON itself, but the unicode-sequences within the JSON string-values.

This test shows the issue in comparison to foundation's stuff - happens in both the `JSONObject` and the `IkigaJSONDecoder`. 
Here is my test snipped:

```
import XCTest
import IkigaJSON
import Foundation
import AnyCodable

final class PayloadTests: XCTestCase {

    func testFoo() throws {
        let json = #"{"foo":"\u00DF"}"#.data(using: .utf8)!
        let o1 = try JSONSerialization.jsonObject(with: json) as! [String: String]
        let o2 = try JSONObject(data: json)
               
        XCTAssertEqual(o1["foo"], "ß") //works
        XCTAssertEqual(o2["foo"]?.string, "ß") //XCTAssertEqual failed: ("nil") is not equal to ("Optional("ß")")

        let o3 = try JSONDecoder().decode(AnyCodable.self, from: json)        
        XCTAssertEqual(o3, ["foo": "ß"]) //works
        
        let o4 = try IkigaJSONDecoder().decode(AnyCodable.self, from: json) //failed: caught error: "dataCorrupted(Swift.DecodingError.Context(codingPath: [], debugDescription: "AnyDecodable value cannot be decoded", underlyingError: nil))"
        XCTAssertEqual(o4, ["foo": "ß"])
    }
}
```
