### ISSUE TITLE
IkigaJSON does not support swift5?

### ISSUE THREAD

**Issue by arden** [orlandos-nl/IkigaJSON#3]
When I used LkigaJSON for ios application in xcode 10.2, I found that swift5 was not supported.

**Comment by Joannis** [comment]
It should work just fine. I'm regularly behind in releasing cocoapod builds compared to SPM builds since my personal primary use cases target SPM. However, my own iOS project running Swift 5 is compiling just fine. Could you post some details about the error you're finding?

**Comment by arden** [comment]
You create an ios project, and then pod 'IkigaJSON', '>= 1.1 ', buid it with an error.

**Comment by Joannis** [comment]
I figured out this morning that SwiftNIO 1.x only supports Swift 4.x compilation mode. But Cocoapods seems to configure that just fine on my end. Things only start failing once I explicitly change its compilation mode to 5.0. Is that what you're doing?

**Comment by Joannis** [comment]
I released a `2.x` IkigaJSON built on top of SwiftNIO 2.0 made only for Swift 5.
