### ISSUE TITLE
Issue with certain escaped unicode sequences in JSON strings

### ISSUE THREAD

**Issue by sliemeobn** [orlandos-nl/IkigaJSON#30]
The fix of #27 seems to still leave a few cases uncovered.

I stumbled over this _"weiß"_ case, which fails with a `JSON Decoder Error`

```swift
func testEscapedUnicode() throws {
    do {
        let json: Data = #"{"foo":"\u0022wei\u00DF\u0022"}"#.data(using: .utf8)!

        let result = try IkigaJSONDecoder().decode([String: String].self, from: json)
        XCTAssertEqual(result, ["foo": #""weiß""#])
    }
}
```

oddly enough, if the string value is just "ß" (without the _wei_) it works...
🍿 can wait to learn what the glitch is here...

**Comment by Joannis** [comment]
Sorry about the slow fixing time, it ended up a bit further down my backlog. But a fix is there now :)
