### ISSUE TITLE
URL decoding as string not supported

### ISSUE THREAD

**Issue by mattpolzin** [orlandos-nl/IkigaJSON#7]
URLs are often encoded as string values in API requests/responses (really, almost any JSON context I would think). The built-in Codable conformance for the Foundation URL type regrettably encodes/decodes to a keyed container instead of a string value. 

JSONEncoder and JSONDecoder of Foundation actually explicitly and unconditionally override this behavior to encode URLs as their `absoluteString` values. 

It would be great if IkigaJSON also either defaulted to (or allowed via an option) decoding/encoding URL values as strings.

**Comment by Joannis** [comment]
Hey, I'm back from vacation. I've added this on my list, unfortunately that won't be this or next week.

**Comment by Kishimotovn** [comment]
@Joannis Hi, do you know if this will be supported soon?
